[tool.poetry]
name = "shadowboxer-client"
version = "0.1.0"
description = ""
authors = ["Sergey <srgpdbd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
